CREATE TABLE "USER"
(
  USERNAME text NOT NULL,
  PASSWORD text NOT NULL,
  ROLE text NOT NULL,
  CONSTRAINT user_pkey PRIMARY KEY (USERNAME)
);

CREATE TABLE COUNTER_TYPE
(
  ID integer NOT NULL,
  NAME text NOT NULL,
  CONSTRAINT counter_type_pkey PRIMARY KEY (ID)
);

CREATE SEQUENCE COUNTER_ID_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE COUNTER
(
  ID integer NOT NULL DEFAULT nextval('COUNTER_ID_SEQ'::regclass),
  NAME text NOT NULL,
  COUNTER_TYPE_ID integer NOT NULL,
  OWNER_USERNAME text NOT NULL,
  CONSTRAINT counter_pkey PRIMARY KEY (ID),
  CONSTRAINT counter_user_fkey FOREIGN KEY (OWNER_USERNAME)
      REFERENCES "USER" (USERNAME) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT counter_type_fkey FOREIGN KEY (COUNTER_TYPE_ID)
      REFERENCES COUNTER_TYPE (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- UNTIL we decide to use One-Many association for values, we may use counter_id as both PK and FK

--CREATE SEQUENCE COUNTER_VALUE_ID_SEQ
--  INCREMENT 1
--  MINVALUE 1
--  MAXVALUE 9223372036854775807
--  START 1
--  CACHE 1;

CREATE TABLE COUNTER_VALUE
(
--  ID integer NOT NULL DEFAULT nextval('COUNTER_VALUE_ID_SEQ'::regclass),
  COUNTER_ID integer,
  COUNTER_VALUE float NOT NULL,
  VALUE_TS timestamp with time zone,
  CONSTRAINT counter_value_pkey PRIMARY KEY (COUNTER_ID),
  CONSTRAINT counter_value_fkey FOREIGN KEY (COUNTER_ID)
      REFERENCES COUNTER (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

INSERT INTO "USER" (USERNAME, PASSWORD, ROLE)
            values ('demo', 'demo', 'ROLE_USER');

INSERT INTO "USER" (USERNAME, PASSWORD, ROLE)
            values ('user', 'user', 'ROLE_USER');

INSERT INTO "USER" (USERNAME, PASSWORD, ROLE)
            values ('admin', 'admin', 'ROLE_ADMIN');

INSERT INTO COUNTER_TYPE (ID, NAME) VALUES (1, 'Hot Water');
INSERT INTO COUNTER_TYPE (ID, NAME) VALUES (2, 'Cold Water');
INSERT INTO COUNTER_TYPE (ID, NAME) VALUES (3, 'Heating');
INSERT INTO COUNTER_TYPE (ID, NAME) VALUES (4, 'Electricity');
